### PR TITLE
Add hover mq variant

### PR DESCRIPTION
**Pull request by f-elix**
This PR adds a variant that we can use to wrap hover styles in a media query, which outputs:

```css
@media (any-hover: hover) {
    hover\:class-name:hover {
        // ...
    }
}
```

This avoids the "sticking" behavior of hover styles on touch devices. 

I am still unsure about what word or character to use for this though. I decided to use an underscore and use it like `_:hover:class-name`, so it is very succint, but I am open to suggestions.

### CODE REVIEW

**Comment by dominic-blain** [comment]
The underscore is a bit weird to me in this situation. "touch" gives you an idea of it's purpose. Maybe this one could be `pointer:hover:bg-red` or `mouse:hover:bg-red`. Not perfect but a lot clearer... I'd like more opinions on this though.

**Comment by f-elix** [comment]
My reasoning with the underscore is that we would completely replace the hover variant with this one, so it should not be much longer to type. Since we would only use this one, it would become a convention and we wouldn't really need to convey it's meaning, we would just know that that's how we write hover styles.

On the other hand, `mouse;hover:classname` is a good compromise and has the benefit of being really clear. 

Maybe I'm just a lazy typer.

**Comment by fhamon** [comment]
@DeuxHuitHuit/maintainers Ping !

**Comment by fhamon** [comment]
@DeuxHuitHuit/review ping !

**Review by fhamon — APPROVED** [review]

**Pull request merged**
